SELECT TOP (1000) [user_id]
      ,[role_id]
      ,[username]
      ,[email]
      ,[password_hash]
      ,[full_name]
      ,[profile_picture]
      ,[bio]
      ,[location]
      ,[last_login]
      ,[is_verified]
  FROM [WellnessWhisperDB].[dbo].[UserDetails]
