# Generated by Django 5.0.9 on 2024-09-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='role',
            new_name='role_id',
        ),
    ]
