# Generated by Django 5.0.9 on 2024-10-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellorprofile',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
    ]
