# Generated by Django 5.0.9 on 2024-10-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_booking_table_alter_calllog_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='chatbotlog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='counsellorprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='moodtracking',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='user_id',
            new_name='user',
        ),
    ]
